#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
#org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
#org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC

# Ajuste equilibrado de memoria
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# Evitar que Kotlin ejecute procesos pesados en paralelo en memoria
kotlin.daemon.jvmargs=-Xmx1524m
org.gradle.configuration-cache=true
org.gradle.caching=true

# Forzar ruta de Android para evitar errores de servicio de localización
systemProp.android.user.home=E:/Proyectos/Terasenior/.android_home
android.nonTransitiveRClass=true
android.useAndroidX=true