#Kotlin
kotlin.code.style=official

# Ajuste de memoria para el Daemon de Kotlin
# Aumentamos para evitar el error "Not enough memory to run compilation"
kotlin.daemon.jvmargs=-Xmx4096m

#Gradle
# Ajuste equilibrado de memoria para el proceso de Gradle
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC

org.gradle.configuration-cache=true
org.gradle.caching=true

# Forzar ruta de Android para evitar errores de servicio de localización
systemProp.android.user.home=E:/Proyectos/Terasenior/.android_home
android.nonTransitiveRClass=true
android.useAndroidX=true
